package aena.model;

// Generated 19-abr-2015 22:55:28 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Aeropuerto generated by hbm2java
 */
public class Aeropuerto implements Serializable {

	private int idAeropuerto;
	private String nombre;
	private String provincia;
	private String direccion;
	private String pais;
	private Set<Vuelo> vuelosForIdAeropuertoSalida = new HashSet<Vuelo>(0);
	private Set<Vuelo> vuelosForIdAeropuertoLlegada = new HashSet<Vuelo>(0);
	private Set<Puerta> puertas = new HashSet<Puerta>(0);

	public Aeropuerto() {
	}

	public Aeropuerto(int idAeropuerto) {
		this.idAeropuerto = idAeropuerto;
	}

	public Aeropuerto(int idAeropuerto, String nombre, String provincia,
			String direccion, String pais,
			Set<Vuelo> vuelosForIdAeropuertoSalida,
			Set<Vuelo> vuelosForIdAeropuertoLlegada, Set<Puerta> puertas) {
		this.idAeropuerto = idAeropuerto;
		this.nombre = nombre;
		this.provincia = provincia;
		this.direccion = direccion;
		this.pais = pais;
		this.vuelosForIdAeropuertoSalida = vuelosForIdAeropuertoSalida;
		this.vuelosForIdAeropuertoLlegada = vuelosForIdAeropuertoLlegada;
		this.puertas = puertas;
	}

	public int getIdAeropuerto() {
		return this.idAeropuerto;
	}

	public void setIdAeropuerto(int idAeropuerto) {
		this.idAeropuerto = idAeropuerto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set<Vuelo> getVuelosForIdAeropuertoSalida() {
		return this.vuelosForIdAeropuertoSalida;
	}

	public void setVuelosForIdAeropuertoSalida(
			Set<Vuelo> vuelosForIdAeropuertoSalida) {
		this.vuelosForIdAeropuertoSalida = vuelosForIdAeropuertoSalida;
	}

	public Set<Vuelo> getVuelosForIdAeropuertoLlegada() {
		return this.vuelosForIdAeropuertoLlegada;
	}

	public void setVuelosForIdAeropuertoLlegada(
			Set<Vuelo> vuelosForIdAeropuertoLlegada) {
		this.vuelosForIdAeropuertoLlegada = vuelosForIdAeropuertoLlegada;
	}

	public Set<Puerta> getPuertas() {
		return this.puertas;
	}

	public void setPuertas(Set<Puerta> puertas) {
		this.puertas = puertas;
	}

}
