package aena.model;

// Generated 20-abr-2015 23:40:24 by Hibernate Tools 3.4.0.CR1

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private int idEmpleado;
	private Aeropuerto aeropuerto;
	private String user;
	private String pass;
	private String dni;
	private String nombre;
	private String apellido;
	private String cargo;

	public Empleado() {
	}

	public Empleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Empleado(int idEmpleado, Aeropuerto aeropuerto, String user,
			String pass, String dni, String nombre, String apellido,
			String cargo) {
		this.idEmpleado = idEmpleado;
		this.aeropuerto = aeropuerto;
		this.user = user;
		this.pass = pass;
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.cargo = cargo;
	}

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Aeropuerto getAeropuerto() {
		return this.aeropuerto;
	}

	public void setAeropuerto(Aeropuerto aeropuerto) {
		this.aeropuerto = aeropuerto;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

}
