package aena.model;

// Generated 19-abr-2015 22:55:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private int idEmpresa;
	private String nombre;
	private String cif;
	private String provincia;
	private String direccion;
	private String pais;
	private Set<Avion> avions = new HashSet<Avion>(0);

	public Empresa() {
	}

	public Empresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public Empresa(int idEmpresa, String nombre, String cif, String provincia,
			String direccion, String pais, Set<Avion> avions) {
		this.idEmpresa = idEmpresa;
		this.nombre = nombre;
		this.cif = cif;
		this.provincia = provincia;
		this.direccion = direccion;
		this.pais = pais;
		this.avions = avions;
	}

	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set<Avion> getAvions() {
		return this.avions;
	}

	public void setAvions(Set<Avion> avions) {
		this.avions = avions;
	}

}
