package aena.model;

// Generated 19-abr-2015 22:55:28 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Pasajero generated by hbm2java
 */
public class Pasajero implements java.io.Serializable {

	private int idPasajero;
	private Vuelo vuelo;
	private Usuario usuario;
	private Date horaEnbarque;
	private Integer asiento;

	public Pasajero() {
	}

	public Pasajero(int idPasajero) {
		this.idPasajero = idPasajero;
	}

	public Pasajero(int idPasajero, Vuelo vuelo, Usuario usuario,
			Date horaEnbarque, Integer asiento) {
		this.idPasajero = idPasajero;
		this.vuelo = vuelo;
		this.usuario = usuario;
		this.horaEnbarque = horaEnbarque;
		this.asiento = asiento;
	}

	public int getIdPasajero() {
		return this.idPasajero;
	}

	public void setIdPasajero(int idPasajero) {
		this.idPasajero = idPasajero;
	}

	public Vuelo getVuelo() {
		return this.vuelo;
	}

	public void setVuelo(Vuelo vuelo) {
		this.vuelo = vuelo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getHoraEnbarque() {
		return this.horaEnbarque;
	}

	public void setHoraEnbarque(Date horaEnbarque) {
		this.horaEnbarque = horaEnbarque;
	}

	public Integer getAsiento() {
		return this.asiento;
	}

	public void setAsiento(Integer asiento) {
		this.asiento = asiento;
	}

}
