package aena.model;

// Generated 19-abr-2015 22:55:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Puerta generated by hbm2java
 */
public class Puerta implements java.io.Serializable {

	private int idPuerta;
	private Aeropuerto aeropuerto;
	private String area;
	private String lugar;
	private String estado;
	private Set<Vuelo> vuelosForIdPuertaLlegada = new HashSet<Vuelo>(0);
	private Set<Vuelo> vuelosForIdPuertaSalida = new HashSet<Vuelo>(0);

	public Puerta() {
	}

	public Puerta(int idPuerta) {
		this.idPuerta = idPuerta;
	}

	public Puerta(int idPuerta, Aeropuerto aeropuerto, String area,
			String lugar, String estado, Set<Vuelo> vuelosForIdPuertaLlegada,
			Set<Vuelo> vuelosForIdPuertaSalida) {
		this.idPuerta = idPuerta;
		this.aeropuerto = aeropuerto;
		this.area = area;
		this.lugar = lugar;
		this.estado = estado;
		this.vuelosForIdPuertaLlegada = vuelosForIdPuertaLlegada;
		this.vuelosForIdPuertaSalida = vuelosForIdPuertaSalida;
	}

	public int getIdPuerta() {
		return this.idPuerta;
	}

	public void setIdPuerta(int idPuerta) {
		this.idPuerta = idPuerta;
	}

	public Aeropuerto getAeropuerto() {
		return this.aeropuerto;
	}

	public void setAeropuerto(Aeropuerto aeropuerto) {
		this.aeropuerto = aeropuerto;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<Vuelo> getVuelosForIdPuertaLlegada() {
		return this.vuelosForIdPuertaLlegada;
	}

	public void setVuelosForIdPuertaLlegada(Set<Vuelo> vuelosForIdPuertaLlegada) {
		this.vuelosForIdPuertaLlegada = vuelosForIdPuertaLlegada;
	}

	public Set<Vuelo> getVuelosForIdPuertaSalida() {
		return this.vuelosForIdPuertaSalida;
	}

	public void setVuelosForIdPuertaSalida(Set<Vuelo> vuelosForIdPuertaSalida) {
		this.vuelosForIdPuertaSalida = vuelosForIdPuertaSalida;
	}

}
