package aena.model;

// Generated 19-abr-2015 22:55:28 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	private int idReserva;
	private Vuelo vuelo;
	private Usuario usuario;
	private Date diaReserva;
	private Date horaReserva;

	public Reserva() {
	}

	public Reserva(int idReserva) {
		this.idReserva = idReserva;
	}

	public Reserva(int idReserva, Vuelo vuelo, Usuario usuario,
			Date diaReserva, Date horaReserva) {
		this.idReserva = idReserva;
		this.vuelo = vuelo;
		this.usuario = usuario;
		this.diaReserva = diaReserva;
		this.horaReserva = horaReserva;
	}

	public int getIdReserva() {
		return this.idReserva;
	}

	public void setIdReserva(int idReserva) {
		this.idReserva = idReserva;
	}

	public Vuelo getVuelo() {
		return this.vuelo;
	}

	public void setVuelo(Vuelo vuelo) {
		this.vuelo = vuelo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getDiaReserva() {
		return this.diaReserva;
	}

	public void setDiaReserva(Date diaReserva) {
		this.diaReserva = diaReserva;
	}

	public Date getHoraReserva() {
		return this.horaReserva;
	}

	public void setHoraReserva(Date horaReserva) {
		this.horaReserva = horaReserva;
	}

}
