package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Froga generated by hbm2java
 */
public class Froga  implements java.io.Serializable {


     private Integer frogazenbakia;
     private Idazkaria idazkaria;
     private Gaixoa gaixoa;
     private Erizaina erizaina;
     private Episodioa episodioa;
     private String gela;
     private Date frogadata;
     private Date frogaordua;
     private Date idazkariakegindakodata;
     private Date sendagileakegindakodata;
     private String deskribapena;
     private String emaitza;
     private boolean ikusia;
     private boolean eginda;

    public Froga() {
    }

    public Froga(Idazkaria idazkaria, Gaixoa gaixoa, Erizaina erizaina, Episodioa episodioa, String gela, Date frogadata, Date frogaordua, Date idazkariakegindakodata, Date sendagileakegindakodata, String deskribapena, String emaitza, boolean ikusia, boolean eginda) {
       this.idazkaria = idazkaria;
       this.gaixoa = gaixoa;
       this.erizaina = erizaina;
       this.episodioa = episodioa;
       this.gela = gela;
       this.frogadata = frogadata;
       this.frogaordua = frogaordua;
       this.idazkariakegindakodata = idazkariakegindakodata;
       this.sendagileakegindakodata = sendagileakegindakodata;
       this.deskribapena = deskribapena;
       this.emaitza = emaitza;
       this.ikusia = ikusia;
       this.eginda = eginda;
    }
   
    public Integer getFrogazenbakia() {
        return this.frogazenbakia;
    }
    
    public void setFrogazenbakia(Integer frogazenbakia) {
        this.frogazenbakia = frogazenbakia;
    }
    public Idazkaria getIdazkaria() {
        return this.idazkaria;
    }
    
    public void setIdazkaria(Idazkaria idazkaria) {
        this.idazkaria = idazkaria;
    }
    public Gaixoa getGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }
    public Erizaina getErizaina() {
        return this.erizaina;
    }
    
    public void setErizaina(Erizaina erizaina) {
        this.erizaina = erizaina;
    }
    public Episodioa getEpisodioa() {
        return this.episodioa;
    }
    
    public void setEpisodioa(Episodioa episodioa) {
        this.episodioa = episodioa;
    }
    public String getGela() {
        return this.gela;
    }
    
    public void setGela(String gela) {
        this.gela = gela;
    }
    public Date getFrogadata() {
        return this.frogadata;
    }
    
    public void setFrogadata(Date frogadata) {
        this.frogadata = frogadata;
    }
    public Date getFrogaordua() {
        return this.frogaordua;
    }
    
    public void setFrogaordua(Date frogaordua) {
        this.frogaordua = frogaordua;
    }
    public Date getIdazkariakegindakodata() {
        return this.idazkariakegindakodata;
    }
    
    public void setIdazkariakegindakodata(Date idazkariakegindakodata) {
        this.idazkariakegindakodata = idazkariakegindakodata;
    }
    public Date getSendagileakegindakodata() {
        return this.sendagileakegindakodata;
    }
    
    public void setSendagileakegindakodata(Date sendagileakegindakodata) {
        this.sendagileakegindakodata = sendagileakegindakodata;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public String getEmaitza() {
        return this.emaitza;
    }
    
    public void setEmaitza(String emaitza) {
        this.emaitza = emaitza;
    }
    public boolean isIkusia() {
        return this.ikusia;
    }
    
    public void setIkusia(boolean ikusia) {
        this.ikusia = ikusia;
    }
    public boolean isEginda() {
        return this.eginda;
    }
    
    public void setEginda(boolean eginda) {
        this.eginda = eginda;
    }




}


