package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LanOrduakSendagileaId generated by hbm2java
 */
public class LanOrduakSendagileaId  implements java.io.Serializable {


     private Date eguna;
     private Date hasiera;
     private Date bukaera;
     private int sendagilezenbakia;

    public LanOrduakSendagileaId() {
    }

    public LanOrduakSendagileaId(Date eguna, Date hasiera, Date bukaera, int sendagilezenbakia) {
       this.eguna = eguna;
       this.hasiera = hasiera;
       this.bukaera = bukaera;
       this.sendagilezenbakia = sendagilezenbakia;
    }
   
    public Date getEguna() {
        return this.eguna;
    }
    
    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }
    public Date getHasiera() {
        return this.hasiera;
    }
    
    public void setHasiera(Date hasiera) {
        this.hasiera = hasiera;
    }
    public Date getBukaera() {
        return this.bukaera;
    }
    
    public void setBukaera(Date bukaera) {
        this.bukaera = bukaera;
    }
    public int getSendagilezenbakia() {
        return this.sendagilezenbakia;
    }
    
    public void setSendagilezenbakia(int sendagilezenbakia) {
        this.sendagilezenbakia = sendagilezenbakia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LanOrduakSendagileaId) ) return false;
		 LanOrduakSendagileaId castOther = ( LanOrduakSendagileaId ) other; 
         
		 return ( (this.getEguna()==castOther.getEguna()) || ( this.getEguna()!=null && castOther.getEguna()!=null && this.getEguna().equals(castOther.getEguna()) ) )
 && ( (this.getHasiera()==castOther.getHasiera()) || ( this.getHasiera()!=null && castOther.getHasiera()!=null && this.getHasiera().equals(castOther.getHasiera()) ) )
 && ( (this.getBukaera()==castOther.getBukaera()) || ( this.getBukaera()!=null && castOther.getBukaera()!=null && this.getBukaera().equals(castOther.getBukaera()) ) )
 && (this.getSendagilezenbakia()==castOther.getSendagilezenbakia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEguna() == null ? 0 : this.getEguna().hashCode() );
         result = 37 * result + ( getHasiera() == null ? 0 : this.getHasiera().hashCode() );
         result = 37 * result + ( getBukaera() == null ? 0 : this.getBukaera().hashCode() );
         result = 37 * result + this.getSendagilezenbakia();
         return result;
   }   


}


