package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA



/**
 * LanOrduakErizaina generated by hbm2java
 */
public class LanOrduakErizaina  implements java.io.Serializable {


     private LanOrduakErizainaId id;
     private Erizaina erizaina;
     private String gela;
     private boolean okupatua;

    public LanOrduakErizaina() {
    }

    public LanOrduakErizaina(LanOrduakErizainaId id, Erizaina erizaina, String gela, boolean okupatua) {
       this.id = id;
       this.erizaina = erizaina;
       this.gela = gela;
       this.okupatua = okupatua;
    }
   
    public LanOrduakErizainaId getId() {
        return this.id;
    }
    
    public void setId(LanOrduakErizainaId id) {
        this.id = id;
    }
    public Erizaina getErizaina() {
        return this.erizaina;
    }
    
    public void setErizaina(Erizaina erizaina) {
        this.erizaina = erizaina;
    }
    public String getGela() {
        return this.gela;
    }
    
    public void setGela(String gela) {
        this.gela = gela;
    }
    public boolean isOkupatua() {
        return this.okupatua;
    }
    
    public void setOkupatua(boolean okupatua) {
        this.okupatua = okupatua;
    }




}


