package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sendagilea generated by hbm2java
 */
public class Sendagilea  implements java.io.Serializable {


     private Integer sendagilezenbakia;
     private Perfil perfil;
     private String dni;
     private String izena;
     private String abizena;
     private String helbidea;
     private String tlf;
     private Date jaiotzedata;
     private String user;
     private String pass;
     private Set<CitaSendagile> citaSendagiles = new HashSet<CitaSendagile>(0);
     private Set<Kontsulta> kontsultas = new HashSet<Kontsulta>(0);
     private Set<LanOrduakSendagilea> lanOrduakSendagileas = new HashSet<LanOrduakSendagilea>(0);
     private Set<Gaixoa> gaixoas = new HashSet<Gaixoa>(0);

    public Sendagilea() {
    }

	
    public Sendagilea(Perfil perfil, String dni, String izena, String abizena, String helbidea, String tlf, Date jaiotzedata, String user, String pass) {
        this.perfil = perfil;
        this.dni = dni;
        this.izena = izena;
        this.abizena = abizena;
        this.helbidea = helbidea;
        this.tlf = tlf;
        this.jaiotzedata = jaiotzedata;
        this.user = user;
        this.pass = pass;
    }
    public Sendagilea(Perfil perfil, String dni, String izena, String abizena, String helbidea, String tlf, Date jaiotzedata, String user, String pass, Set<CitaSendagile> citaSendagiles, Set<Kontsulta> kontsultas, Set<LanOrduakSendagilea> lanOrduakSendagileas, Set<Gaixoa> gaixoas) {
       this.perfil = perfil;
       this.dni = dni;
       this.izena = izena;
       this.abizena = abizena;
       this.helbidea = helbidea;
       this.tlf = tlf;
       this.jaiotzedata = jaiotzedata;
       this.user = user;
       this.pass = pass;
       this.citaSendagiles = citaSendagiles;
       this.kontsultas = kontsultas;
       this.lanOrduakSendagileas = lanOrduakSendagileas;
       this.gaixoas = gaixoas;
    }
   
    public Integer getSendagilezenbakia() {
        return this.sendagilezenbakia;
    }
    
    public void setSendagilezenbakia(Integer sendagilezenbakia) {
        this.sendagilezenbakia = sendagilezenbakia;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena() {
        return this.abizena;
    }
    
    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }
    public Date getJaiotzedata() {
        return this.jaiotzedata;
    }
    
    public void setJaiotzedata(Date jaiotzedata) {
        this.jaiotzedata = jaiotzedata;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set<CitaSendagile> getCitaSendagiles() {
        return this.citaSendagiles;
    }
    
    public void setCitaSendagiles(Set<CitaSendagile> citaSendagiles) {
        this.citaSendagiles = citaSendagiles;
    }
    public Set<Kontsulta> getKontsultas() {
        return this.kontsultas;
    }
    
    public void setKontsultas(Set<Kontsulta> kontsultas) {
        this.kontsultas = kontsultas;
    }
    public Set<LanOrduakSendagilea> getLanOrduakSendagileas() {
        return this.lanOrduakSendagileas;
    }
    
    public void setLanOrduakSendagileas(Set<LanOrduakSendagilea> lanOrduakSendagileas) {
        this.lanOrduakSendagileas = lanOrduakSendagileas;
    }
    public Set<Gaixoa> getGaixoas() {
        return this.gaixoas;
    }
    
    public void setGaixoas(Set<Gaixoa> gaixoas) {
        this.gaixoas = gaixoas;
    }




}


