package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CitaSendagileId generated by hbm2java
 */
public class CitaSendagileId  implements java.io.Serializable {


     private int idazkarizenbakia;
     private int gaixozenbakia;
     private int sendagilezenbakia;
     private Date data;

    public CitaSendagileId() {
    }

    public CitaSendagileId(int idazkarizenbakia, int gaixozenbakia, int sendagilezenbakia, Date data) {
       this.idazkarizenbakia = idazkarizenbakia;
       this.gaixozenbakia = gaixozenbakia;
       this.sendagilezenbakia = sendagilezenbakia;
       this.data = data;
    }
   
    public int getIdazkarizenbakia() {
        return this.idazkarizenbakia;
    }
    
    public void setIdazkarizenbakia(int idazkarizenbakia) {
        this.idazkarizenbakia = idazkarizenbakia;
    }
    public int getGaixozenbakia() {
        return this.gaixozenbakia;
    }
    
    public void setGaixozenbakia(int gaixozenbakia) {
        this.gaixozenbakia = gaixozenbakia;
    }
    public int getSendagilezenbakia() {
        return this.sendagilezenbakia;
    }
    
    public void setSendagilezenbakia(int sendagilezenbakia) {
        this.sendagilezenbakia = sendagilezenbakia;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CitaSendagileId) ) return false;
		 CitaSendagileId castOther = ( CitaSendagileId ) other; 
         
		 return (this.getIdazkarizenbakia()==castOther.getIdazkarizenbakia())
 && (this.getGaixozenbakia()==castOther.getGaixozenbakia())
 && (this.getSendagilezenbakia()==castOther.getSendagilezenbakia())
 && ( (this.getData()==castOther.getData()) || ( this.getData()!=null && castOther.getData()!=null && this.getData().equals(castOther.getData()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdazkarizenbakia();
         result = 37 * result + this.getGaixozenbakia();
         result = 37 * result + this.getSendagilezenbakia();
         result = 37 * result + ( getData() == null ? 0 : this.getData().hashCode() );
         return result;
   }   


}


