package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Erizaina generated by hbm2java
 */
public class Erizaina  implements java.io.Serializable {


     private Integer erizainzenbakia;
     private Perfil perfil;
     private String dni;
     private String izena;
     private String abizena;
     private String helbidea;
     private String tlf;
     private Date jaiotzedata;
     private String user;
     private String pass;
     private Set<LanOrduakErizaina> lanOrduakErizainas = new HashSet<LanOrduakErizaina>(0);
     private Set<Froga> frogas = new HashSet<Froga>(0);

    public Erizaina() {
    }

	
    public Erizaina(Perfil perfil, String dni, String izena, String abizena, String helbidea, String tlf, Date jaiotzedata, String user, String pass) {
        this.perfil = perfil;
        this.dni = dni;
        this.izena = izena;
        this.abizena = abizena;
        this.helbidea = helbidea;
        this.tlf = tlf;
        this.jaiotzedata = jaiotzedata;
        this.user = user;
        this.pass = pass;
    }
    public Erizaina(Perfil perfil, String dni, String izena, String abizena, String helbidea, String tlf, Date jaiotzedata, String user, String pass, Set<LanOrduakErizaina> lanOrduakErizainas, Set<Froga> frogas) {
       this.perfil = perfil;
       this.dni = dni;
       this.izena = izena;
       this.abizena = abizena;
       this.helbidea = helbidea;
       this.tlf = tlf;
       this.jaiotzedata = jaiotzedata;
       this.user = user;
       this.pass = pass;
       this.lanOrduakErizainas = lanOrduakErizainas;
       this.frogas = frogas;
    }
   
    public Integer getErizainzenbakia() {
        return this.erizainzenbakia;
    }
    
    public void setErizainzenbakia(Integer erizainzenbakia) {
        this.erizainzenbakia = erizainzenbakia;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getAbizena() {
        return this.abizena;
    }
    
    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }
    public Date getJaiotzedata() {
        return this.jaiotzedata;
    }
    
    public void setJaiotzedata(Date jaiotzedata) {
        this.jaiotzedata = jaiotzedata;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public Set<LanOrduakErizaina> getLanOrduakErizainas() {
        return this.lanOrduakErizainas;
    }
    
    public void setLanOrduakErizainas(Set<LanOrduakErizaina> lanOrduakErizainas) {
        this.lanOrduakErizainas = lanOrduakErizainas;
    }
    public Set<Froga> getFrogas() {
        return this.frogas;
    }
    
    public void setFrogas(Set<Froga> frogas) {
        this.frogas = frogas;
    }




}


