package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Errezeta generated by hbm2java
 */
public class Errezeta  implements java.io.Serializable {


     private Integer errezetazenbakia;
     private Episodioa episodioa;
     private Date emandakodata;
     private String deskribapena;
     private String kantitatea;

    public Errezeta() {
    }

    public Errezeta(Episodioa episodioa, Date emandakodata, String deskribapena, String kantitatea) {
       this.episodioa = episodioa;
       this.emandakodata = emandakodata;
       this.deskribapena = deskribapena;
       this.kantitatea = kantitatea;
    }
   
    public Integer getErrezetazenbakia() {
        return this.errezetazenbakia;
    }
    
    public void setErrezetazenbakia(Integer errezetazenbakia) {
        this.errezetazenbakia = errezetazenbakia;
    }
    public Episodioa getEpisodioa() {
        return this.episodioa;
    }
    
    public void setEpisodioa(Episodioa episodioa) {
        this.episodioa = episodioa;
    }
    public Date getEmandakodata() {
        return this.emandakodata;
    }
    
    public void setEmandakodata(Date emandakodata) {
        this.emandakodata = emandakodata;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public String getKantitatea() {
        return this.kantitatea;
    }
    
    public void setKantitatea(String kantitatea) {
        this.kantitatea = kantitatea;
    }




}


