package model;
// Generated 08-ene-2013 2:46:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer perfilzenbakia;
     private String deskribapena;
     private boolean gaixoa;
     private boolean gaixoberria;
     private boolean bilatuhistorial;
     private boolean cita;
     private boolean gaurkoproba;
     private boolean gaurkokontsulta;
     private boolean emancita;
     private boolean ordutegia;
     private boolean ordutegiakontsultatu;
     private boolean ordutegiajarri;
     private Set<Erizaina> erizainas = new HashSet<Erizaina>(0);
     private Set<Idazkaria> idazkarias = new HashSet<Idazkaria>(0);
     private Set<Sendagilea> sendagileas = new HashSet<Sendagilea>(0);

    public Perfil() {
    }

	
    public Perfil(String deskribapena, boolean gaixoa, boolean gaixoberria, boolean bilatuhistorial, boolean cita, boolean gaurkoproba, boolean gaurkokontsulta, boolean emancita, boolean ordutegia, boolean ordutegiakontsultatu, boolean ordutegiajarri) {
        this.deskribapena = deskribapena;
        this.gaixoa = gaixoa;
        this.gaixoberria = gaixoberria;
        this.bilatuhistorial = bilatuhistorial;
        this.cita = cita;
        this.gaurkoproba = gaurkoproba;
        this.gaurkokontsulta = gaurkokontsulta;
        this.emancita = emancita;
        this.ordutegia = ordutegia;
        this.ordutegiakontsultatu = ordutegiakontsultatu;
        this.ordutegiajarri = ordutegiajarri;
    }
    public Perfil(String deskribapena, boolean gaixoa, boolean gaixoberria, boolean bilatuhistorial, boolean cita, boolean gaurkoproba, boolean gaurkokontsulta, boolean emancita, boolean ordutegia, boolean ordutegiakontsultatu, boolean ordutegiajarri, Set<Erizaina> erizainas, Set<Idazkaria> idazkarias, Set<Sendagilea> sendagileas) {
       this.deskribapena = deskribapena;
       this.gaixoa = gaixoa;
       this.gaixoberria = gaixoberria;
       this.bilatuhistorial = bilatuhistorial;
       this.cita = cita;
       this.gaurkoproba = gaurkoproba;
       this.gaurkokontsulta = gaurkokontsulta;
       this.emancita = emancita;
       this.ordutegia = ordutegia;
       this.ordutegiakontsultatu = ordutegiakontsultatu;
       this.ordutegiajarri = ordutegiajarri;
       this.erizainas = erizainas;
       this.idazkarias = idazkarias;
       this.sendagileas = sendagileas;
    }
   
    public Integer getPerfilzenbakia() {
        return this.perfilzenbakia;
    }
    
    public void setPerfilzenbakia(Integer perfilzenbakia) {
        this.perfilzenbakia = perfilzenbakia;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public boolean isGaixoa() {
        return this.gaixoa;
    }
    
    public void setGaixoa(boolean gaixoa) {
        this.gaixoa = gaixoa;
    }
    public boolean isGaixoberria() {
        return this.gaixoberria;
    }
    
    public void setGaixoberria(boolean gaixoberria) {
        this.gaixoberria = gaixoberria;
    }
    public boolean isBilatuhistorial() {
        return this.bilatuhistorial;
    }
    
    public void setBilatuhistorial(boolean bilatuhistorial) {
        this.bilatuhistorial = bilatuhistorial;
    }
    public boolean isCita() {
        return this.cita;
    }
    
    public void setCita(boolean cita) {
        this.cita = cita;
    }
    public boolean isGaurkoproba() {
        return this.gaurkoproba;
    }
    
    public void setGaurkoproba(boolean gaurkoproba) {
        this.gaurkoproba = gaurkoproba;
    }
    public boolean isGaurkokontsulta() {
        return this.gaurkokontsulta;
    }
    
    public void setGaurkokontsulta(boolean gaurkokontsulta) {
        this.gaurkokontsulta = gaurkokontsulta;
    }
    public boolean isEmancita() {
        return this.emancita;
    }
    
    public void setEmancita(boolean emancita) {
        this.emancita = emancita;
    }
    public boolean isOrdutegia() {
        return this.ordutegia;
    }
    
    public void setOrdutegia(boolean ordutegia) {
        this.ordutegia = ordutegia;
    }
    public boolean isOrdutegiakontsultatu() {
        return this.ordutegiakontsultatu;
    }
    
    public void setOrdutegiakontsultatu(boolean ordutegiakontsultatu) {
        this.ordutegiakontsultatu = ordutegiakontsultatu;
    }
    public boolean isOrdutegiajarri() {
        return this.ordutegiajarri;
    }
    
    public void setOrdutegiajarri(boolean ordutegiajarri) {
        this.ordutegiajarri = ordutegiajarri;
    }
    public Set<Erizaina> getErizainas() {
        return this.erizainas;
    }
    
    public void setErizainas(Set<Erizaina> erizainas) {
        this.erizainas = erizainas;
    }
    public Set<Idazkaria> getIdazkarias() {
        return this.idazkarias;
    }
    
    public void setIdazkarias(Set<Idazkaria> idazkarias) {
        this.idazkarias = idazkarias;
    }
    public Set<Sendagilea> getSendagileas() {
        return this.sendagileas;
    }
    
    public void setSendagileas(Set<Sendagilea> sendagileas) {
        this.sendagileas = sendagileas;
    }




}


