// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.aena.domain;

import com.aena.domain.Avion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Avion_Roo_Configurable {
    
    declare @type: Avion: @Configurable;
    
}
